[package]
name = "ate"
version = "1.0.0"
edition = "2021"
authors = ["AnmiTaliDev <anmitalidev@nuros.org>"]
description = "AnmiTali Encryption — Linux file encryption utility"
license = "MPL-2.0"

[[bin]]
name = "ate"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
aes = "0.9.0-rc.0"
twofish = "0.8.0-rc.0"
serpent = "0.6.0-rc.3"
cbc = { version = "0.2.0-rc.3", features = ["alloc", "block-padding"] }
pbkdf2 = { version = "0.12", features = ["hmac"] }
sha2 = "0.10"
rand = "0.8"
hmac = "0.12"
anyhow = "1"
indicatif = "0.17"
zeroize = { version = "1", features = ["derive"] }
cipher = { version = "0.5", features = ["alloc", "block-padding"] }
